{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serviceexample.fullname" . }}-mongo
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "serviceexample.name" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "serviceexample.name" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "appdb"
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          {{- if .Values.mongodb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "serviceexample.fullname" . }}-mongo-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceexample.fullname" . }}-mongo
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    component: mongo
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    app: {{ include "serviceexample.name" . }}-mongo
---
{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "serviceexample.fullname" . }}-mongo-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
