{{- if .Values.nats.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serviceexample.fullname" . }}-nats
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    component: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "serviceexample.name" . }}-nats
  template:
    metadata:
      labels:
        app: {{ include "serviceexample.name" . }}-nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
          ports:
            - name: nats
              containerPort: 4222
          args:
            - "--server_name"
            - "nats-main"
            - "--http_port"
            - "8222"
            {{- if .Values.nats.persistence.enabled }}
            - "--jetstream"
            {{- end }}
          resources:
            {{- toYaml .Values.nats.resources | nindent 12 }}
      {{- if .Values.nats.persistence.enabled }}
      volumes:
        - name: nats-data
          emptyDir: {}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceexample.fullname" . }}-nats
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    component: nats
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  selector:
    app: {{ include "serviceexample.name" . }}-nats
{{- end }}
