apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceexample.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "serviceexample.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "serviceexample.selectorLabels" . | nindent 4 }}

