apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-csi
spec:
  releaseName: hcloud-csi
  chart:
    spec:
      chart: hcloud-csi
      sourceRef:
        kind: HelmRepository
        name: hcloud
  interval: 15m
  timeout: 5m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: values-hcloud-csi