apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-repo.yaml
- helm-release.yaml
namespace: kube-system
configurations:
- kustomizeconfig.yaml
configMapGenerator:
- name: values-hcloud-csi
  files:
  - values.yaml=values-public.yaml