apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      version: ">=1.15.0-0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
