apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: serviceexample
spec:
  releaseName: serviceexample
  targetNamespace: serviceexample
  chart:
    spec:
      chart: charts/serviceexample
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  # valuesFrom:
  # - kind: ConfigMap
  #   name: values-serviceexample
