apiVersion: v2
name: serviceexample
description: A .NET 9 service using MongoDB, Redis and NATS.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb
    version: 15.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: redis
    version: 19.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: nats
    version: 1.2.2
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled

icon: https://raw.githubusercontent.com/oxxenix/ServiceExample-copy/main/logo.png

home: https://github.com/oxxenix/ServiceExample-copy
sources:
  - https://github.com/oxxenix/ServiceExample-copy
keywords: [dotnet, mongodb, redis, nats, aspire, kubernetes, helm]

maintainers:
  - name: oxxenix
    email: oksana.baranova@intel.com
    url: https://github.com/oxxenix

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Initial production-ready Helm chart for ServiceExample (.NET 9).
    - Added MongoDB, Redis, and NATS subcharts.
    - Includes schema validation and OCI publishing metadata.
  artifacthub.io/images: |
    - name: serviceexample
      image: ghcr.io/oxxenix/serviceexample:latest
  artifacthub.io/category: application