image:
  repository: ghcr.io/oxxenix/serviceexample
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

namespace:
  name: serviceexample
  create: true

service:
  type: ClusterIP
  port: 9080
  targetPort: 9080
  annotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:9080"
  Aspire__MongoDB__Driver__ConnectionString: "mongodb://serviceexample-mongodb:27017"
  Aspire__StackExchange__Redis__ConnectionString: "serviceexample-redis-master:6379"
  Aspire__NATS__Net__ConnectionString: "nats://serviceexample-nats:4222"

livenessProbe:
  httpGet:
    path: /
    port: 9080
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 6

readinessProbe:
  httpGet:
    path: /
    port: 9080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 10000
  allowPrivilegeEscalation: false

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}

# Multi-arch env
archSelector:
  enabled: false
  arch: amd64


# MongoDB
mongodb:
  enabled: true
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi


# Redis
redis:
  enabled: true
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# NATS
nats:
  enabled: true
  image:
    repository: nats
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 4222
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
