name: Helm Chart CI

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/serviceexample/**'
      - '.github/workflows/helm-ci.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/serviceexample/**'
      - '.github/workflows/helm-ci.yaml'

jobs:
  lint:
    name: Check Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.15.4

      - name: Lint Helm chart
        run:  helm lint charts/serviceexample

      - name: Helm template validation
        run:  helm template charts/serviceexample --debug > /dev/null  

  package-and-publish:
    name: Package & publish to GitHub pages
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          mkdir -p ./gh-pages
          helm package charts/serviceexample --destination ./gh-pages
          helm repo index ./gh-pages --url https://oxxenix.github.io/ServiceExample-copy

      - name: Deploy Helm chart to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
          keep_files: true
  